name : "Deploy to Production"
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: "Deploy to Production"
    runs-on: ubuntu-latest

    steps:
      - id: 'Checkout'
        name: "Checkout code"
        uses: actions/checkout@v3

      - id: "Auth"
        name: "Authenticate to Cloud Provider"
        uses: google-github-actions/auth@v3 #ngantuk jir kenapa 4
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - id: 'SetupTerraform'
        name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2

      - id: 'SecurityScan'
        name: "Security Scan"
        uses: aquasecurity/tfsec-action@v1.0.0

      - id: 'TerraformInit'
        name: "Terraform Init"
        run: terraform init

      - id: 'InjectTfvars'
        name: "Inject TF Vars"
        run: echo "${{ secrets.GLOBAL_TFVARS }}" > global.tfvars

      - id: 'TerraformLint'
        name: "Terraform Lint"
        run: terraform fmt

      - id: 'TerraformPlan'
        name: "Terraform Plan"
        run: terraform plan -out=tfplan -var-file=global.tfvars

      - id: 'TerraformApply'
        name: "Terraform Apply"
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan -var-file=global.tfvars