name : "Terraform CI/CD & Security Checks"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: "Terraform CI/CD & Security Checks"
    runs-on: ubuntu-latest

    steps:
      - id: 'Checkout'
        name: "Checkout code"
        uses: actions/checkout@v3

      - id: "Auth"
        name: "Authenticate to Cloud Provider"
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - id: 'SetupTerraform'
        name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2

      - id: 'SecurityScan'
        name: "Security Scan"
        uses: aquasec/tfsec-action@v1

      - id: 'TerraformInit'
        name: "Terraform Init"
        run: terraform init

      - id: 'TerraformLint'
        name: "Terraform Lint"
        run: terraform fmt -check

      - id: 'TerraformPlan'
        name: "Terraform Plan"
        run: terraform plan -out=tfplan

      - id: 'TerraformApply'
        name: "Terraform Apply"
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan